#!/bin/sh
set -e
set -u

case "$1" in
remove)
  ianadir=/var/lib/snmp/mibs/iana
  ietfdir=/var/lib/snmp/mibs/ietf

  for mib in $(download-mibs --list iana) $(download-mibs --list ianarfc); do
    rm -f $ianadir/$mib
  done
  rmdir --ignore-fail-on-non-empty $ianadir

  for mib in $(download-mibs --list rfc); do
    rm -f $ietfdir/$mib
  done
  rmdir --ignore-fail-on-non-empty $ietfdir
  ;;
esac

#DEBHELPER#
